## Debugging

### TensorFlow debugger (tfdbg) 


In [8]:
import tensorflow as tf

sess = tf.Session()
input = tf.placeholder(tf.float32, [None, 2, 2])
input.get_shape(), tf.shape(input), sess.run(tf.shape(input), feed_dict={input: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]})

(TensorShape([Dimension(None), Dimension(2), Dimension(2)]),
 <tf.Tensor 'Shape_6:0' shape=(3,) dtype=int32>,
 array([2, 2, 2], dtype=int32))

In [12]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
t.get_shape(), tf.shape(t), sess.run(tf.shape(t)), sess.run(t)

(TensorShape([Dimension(2), Dimension(2), Dimension(3)]),
 <tf.Tensor 'Shape_12:0' shape=(3,) dtype=int32>,
 array([2, 2, 3], dtype=int32),
 array([[[1, 1, 1],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [4, 4, 4]]], dtype=int32))