In [2]:
import tensorflow as tf
import numpy as np

`tf.nn.embedding_lookup`

In [2]:
input_ids = tf.placeholder(tf.int32, shape=[None])
embedding = tf.Variable(np.identity(5, dtype=np.float32))
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [3]:
embedding.eval()

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]], dtype=float32)

In [4]:
sess.run(input_embedding, feed_dict={input_ids: [1, 2, 3, 0, 3, 2, 1, 0]})

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]], dtype=float32)

In [5]:
input_ids = tf.placeholder(tf.int32)
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)
sess.run(input_embedding, feed_dict={input_ids:[[1, 2], [2, 1], [3, 3], [1, 1]]})

array([[[ 0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.,  0.]],

       [[ 0.,  1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.]]], dtype=float32)

In [6]:
tf.placeholder?

In [4]:
tf.nn.embedding_lookup?