In [2]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
print(mx.__version__)

1.0.0


In [7]:
x = nd.empty((3, 4))
print(x)
x = nd.zeros((3, 5), mx.cpu(0))
print(x)
import numpy as np
 
x = nd.ones((3, 4), ctx=mx.cpu(0), dtype=np.float32)
print(x)


[[-2.8498595e-20  3.0747291e-41  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]
<NDArray 3x4 @cpu(0)>

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<NDArray 3x5 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [8]:
np_x = np.arange(12)
mx_x = nd.array(np_x)
type(np_x), type(mx_x), type(mx_x.asnumpy())

(numpy.ndarray, mxnet.ndarray.ndarray.NDArray, numpy.ndarray)

In [9]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[ 0.03958665  0.69854546 -1.3777038  -0.95514274]
 [-0.3140079   0.6033493   1.471269   -1.5130569 ]
 [ 0.5505674   0.4113778   1.7742808  -0.09882127]]
<NDArray 3x4 @cpu(0)>

In [10]:
y.shape

(3, 4)

In [11]:
y.size

12

In [13]:
x + y, x * y, x / y, nd.exp(y), nd.dot(x, y.T)

(
 [[ 1.0395867   1.6985455  -0.3777038   0.04485726]
  [ 0.6859921   1.6033493   2.4712691  -0.5130569 ]
  [ 1.5505674   1.4113778   2.7742808   0.9011787 ]]
 <NDArray 3x4 @cpu(0)>, 
 [[ 0.03958665  0.69854546 -1.3777038  -0.95514274]
  [-0.3140079   0.6033493   1.471269   -1.5130569 ]
  [ 0.5505674   0.4113778   1.7742808  -0.09882127]]
 <NDArray 3x4 @cpu(0)>, 
 [[ 25.26104      1.4315461   -0.72584546  -1.0469639 ]
  [ -3.1846333    1.6574147    0.67968535  -0.6609137 ]
  [  1.8163081    2.4308555    0.56360865 -10.119279  ]]
 <NDArray 3x4 @cpu(0)>, 
 [[1.0403806  2.0108256  0.25215688 0.38475722]
  [0.7305133  1.8282319  4.354758   0.22023572]
  [1.7342367  1.5088953  5.896039   0.9059046 ]]
 <NDArray 3x4 @cpu(0)>, 
 [[-1.5947144   0.24755359  2.637405  ]
  [-1.5947144   0.24755359  2.637405  ]
  [-1.5947144   0.24755359  2.637405  ]]
 <NDArray 3x3 @cpu(0)>)

In [17]:
print(id(y))
y = y + x
print(id(y))
y[:] = x + y
print(id(y))
nd.elemwise_add(x, y, out=y)
print(id(y))
y += x
print(id(y))

140691382983928
140690200780080
140690200780080
140690200780080
140690200780080


In [19]:
x[1:3]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 2x4 @cpu(0)>

In [21]:
x[1, 2] = 8.0
x


[[1. 1. 1. 1.]
 [1. 1. 8. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [23]:
x[1:2,1:3]


[[1. 8.]]
<NDArray 1x2 @cpu(0)>

In [25]:
x[1:2,1:3] = 5.0
x


[[1. 1. 1. 1.]
 [1. 5. 5. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

## Broadcasting

where we compose a low dimensional array y with a high-dimensional array X invoke a functionality called broadcasting. Here, the low-dimensional array is duplicated along any axis with dimension 1 to match the shape of the high dimensional array.

In [4]:
x = nd.ones(shape=(3, 3))
x


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>

In [6]:
x = nd.arange(3).reshape((3, 1))
y = nd.arange(2).reshape((1, 2))
x, y, x + y

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>, 
 [[0. 1.]
  [1. 2.]
  [2. 3.]]
 <NDArray 3x2 @cpu(0)>)

In [29]:
y = nd.arange(3)
y


[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [30]:
x + y


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
<NDArray 3x3 @cpu(0)>

- While y is initially of shape (3), MXNet infers its shape to be (1,3), and then broadcasts along the rows to form a (3,3) matrix).
- ** broadcasting prefers to duplicate along the left most axis. **

In [32]:
y = y.reshape((3, 1))
y


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [33]:
x + y


[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
<NDArray 3x3 @cpu(0)>

In [35]:
type(x.asnumpy())

numpy.ndarray

In [36]:
nd.array(x.asnumpy())


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>

- In MXNet, every array has a context. 
-  By assigning arrays to contexts intelligently, we can minimize the time spent transferring data between devices

In [3]:
z = nd.ones(shape=(3, 3), ctx=mx.gpu(0))

In [4]:
z


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @gpu(0)>

In [7]:
z_cpu = z.copyto(mx.cpu(0))
z_cpu


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>

- The result of an operator will have the same context as the inputs.
- In order to perform an operation on two ndarrays x1 and x2, we need them both to live on the same context.
- But transferring variables between different contexts is slow. So we want you to be 100% certain that you want to do something slow before we let you do it. 


![](http://gluon.mxnet.io/_images/operator-context.png)


- Imagine that your variable z already lives on your second GPU (gpu(0)). What happens if we call `z.copyto(gpu(0))`? It will make a copy and allocate new memory, even though that variable already lives on the desired device!
- we can call `as_in_context()`. If the variable is already the specified context then this is a no-op

In [8]:
z_cpu + z_cpu


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
<NDArray 3x3 @cpu(0)>

In [9]:
z + z


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
<NDArray 3x3 @gpu(0)>

In [10]:
z + z_cpu

MXNetError: [15:03:57] src/imperative/./imperative_utils.h:55: Check failed: inputs[i]->ctx().dev_mask() == ctx.dev_mask() (1 vs. 2) Operator broadcast_add require all inputs live on the same context. But the first argument is on gpu(0) while the 2-th argument is on cpu(0)

Stack trace returned 10 entries:
[bt] (0) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5a) [0x7f57e31d12fa]
[bt] (1) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f57e31d1e98]
[bt] (2) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::imperative::GetContext(nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, mxnet::Context const&)+0x52d) [0x7f57e58ac25d]
[bt] (3) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x335) [0x7f57e588def5]
[bt] (4) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**)+0xe7b) [0x7f57e5d828ab]
[bt] (5) /home/zhenglai/repo/incubator-mxnet/python/mxnet/../../lib/libmxnet.so(MXImperativeInvokeEx+0x3ff) [0x7f57e5d8406f]
[bt] (6) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f587a1abe20]
[bt] (7) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x2eb) [0x7f587a1ab88b]
[bt] (8) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x49a) [0x7f587a1a601a]
[bt] (9) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x9fcb) [0x7f587a199fcb]



In [11]:
z.context, z_cpu.context

(gpu(0), cpu(0))

In [13]:
id(z)

140014706777112

In [15]:
z = z.copyto(mx.gpu(0))
id(z)

140014705524688

In [17]:
z = z.as_in_context(mx.gpu(0))
id(z)

140014705524688