In [2]:
from mxnet import nd

In [4]:

##########################
# Instantiate two scalars
##########################
x = nd.array([3.0])
y = nd.array([2.0])

##########################
# Add them
##########################
print('x + y = ', x + y)

##########################
# Multiply them
##########################
print('x * y = ', x * y)

##########################
# Divide x by y
##########################
print('x / y = ', x / y)

##########################
# Raise x to the power y.
##########################
print('x ** y = ', nd.power(x,y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


In [6]:
# We can convert any NDArray to a Python float by calling its asscalar method
x.asscalar()

3.0

In [7]:
# vector
u = nd.arange(4)
print('u = ', u)

u =  
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>


In [8]:
len(u)

4

In [9]:
u.shape

(4,)

In [11]:
a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


In [12]:
# matrices
x = nd.arange(20)
A = x.reshape((5, 4))
A


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

In [13]:
print('A[2, 3] = ', A[2, 3])

A[2, 3] =  
[11.]
<NDArray 1 @cpu(0)>


In [14]:
print('row 2', A[2, :])
print('column 3', A[:, 3])

row 2 
[ 8.  9. 10. 11.]
<NDArray 4 @cpu(0)>
column 3 
[ 3.  7. 11. 15. 19.]
<NDArray 5 @cpu(0)>


In [16]:
A.T


[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>

### Tensors
- Vectors, for example, are first-order tensors, and matrices are second-order tensors.
-  In MXNet, the common standard arithmetic operators (+,-,/,*,**) have all been lifted to element-wise operations for identically-shaped tensors of arbitrary shape.

In [17]:
X = nd.arange(24).reshape((2, 3, 4))

In [19]:
X, X.shape, X.size

(
 [[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]]
 
  [[12. 13. 14. 15.]
   [16. 17. 18. 19.]
   [20. 21. 22. 23.]]]
 <NDArray 2x3x4 @cpu(0)>, (2, 3, 4), 24)

In [20]:
u = nd.array([1, 2, 4, 8])
v = nd.ones_like(u) * 2
print('v =', v)
print('u + v', u + v)
print('u - v', u - v)
print('u * v', u * v)
print('u / v', u / v)

v = 
[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>
u + v 
[ 3.  4.  6. 10.]
<NDArray 4 @cpu(0)>
u - v 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
u * v 
[ 2.  4.  8. 16.]
<NDArray 4 @cpu(0)>
u / v 
[0.5 1.  2.  4. ]
<NDArray 4 @cpu(0)>


In [21]:
B = nd.ones_like(A) * 3
print('B =', B)
print('A + B =', A + B)
print('A * B =', A * B)

B = 
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
<NDArray 5x4 @cpu(0)>
A + B = 
[[ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]
 [11. 12. 13. 14.]
 [15. 16. 17. 18.]
 [19. 20. 21. 22.]]
<NDArray 5x4 @cpu(0)>
A * B = 
[[ 0.  3.  6.  9.]
 [12. 15. 18. 21.]
 [24. 27. 30. 33.]
 [36. 39. 42. 45.]
 [48. 51. 54. 57.]]
<NDArray 5x4 @cpu(0)>


In [22]:
u


[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>

In [24]:
nd.sum(u), nd.mean(u), nd.sum(u) / u.size

(
 [15.]
 <NDArray 1 @cpu(0)>, 
 [3.75]
 <NDArray 1 @cpu(0)>, 
 [3.75]
 <NDArray 1 @cpu(0)>)

In [26]:
v


[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>

In [28]:
nd.dot(u, v), nd.sum(u * v)

(
 [30.]
 <NDArray 1 @cpu(0)>, 
 [30.]
 <NDArray 1 @cpu(0)>)

Dot products are useful in a wide range of contexts.
- When the weights are non-negative and sum to one (∑di=1wi=1), the dot product expresses a weighted average.
- When two vectors each have length one (we’ll discuss what length means below in the section on norms), dot products can also capture the cosine of the angle between them.

- So you can think of multiplication by a matrix A∈ℝm×n as a transformation that projects vectors from ℝm to ℝn.
- we can represent rotations as multiplications by a square matrix.

In [29]:
A, u

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]
  [16. 17. 18. 19.]]
 <NDArray 5x4 @cpu(0)>, 
 [1. 2. 4. 8.]
 <NDArray 4 @cpu(0)>)

In [32]:
nd.dot(A, u), nd.dot(A, u.reshape((4, 1)))

(
 [ 34.  94. 154. 214. 274.]
 <NDArray 5 @cpu(0)>, 
 [[ 34.]
  [ 94.]
  [154.]
  [214.]
  [274.]]
 <NDArray 5x1 @cpu(0)>)

In [35]:
A = nd.ones(shape=(3, 4))
B = nd.ones(shape=(4, 5))
nd.dot(A, B)


[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
<NDArray 3x5 @cpu(0)>

In [36]:
u


[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>

In [39]:
nd.norm(u) # L2 norm


[9.219544]
<NDArray 1 @cpu(0)>

In [40]:
nd.sum(nd.abs(u)) # L1 norm


[15.]
<NDArray 1 @cpu(0)>