In [2]:
import mxnet as mx
from mxnet import nd

In [18]:
def softmax(X):
    ex = nd.exp(X)
    su = ex.sum(axis=1, keepdims=True)
    print(X.shape, su.shape)
    return ex / su

In [37]:
X = nd.random_normal(shape=(2, 5))
X_prob = softmax(X)
X, X_prob, X_prob.sum(axis=1)

(2, 5) (2, 1)


(
 [[-0.03865968 -0.18256646 -0.63579154 -1.0019276  -0.23578128]
  [ 1.3968942  -0.3896926   0.0197017  -0.74442834 -0.15309551]]
 <NDArray 2x5 @cpu(0)>, 
 [[0.2763125  0.23927791 0.15207906 0.10545291 0.22687764]
  [0.5715702  0.09575573 0.14419907 0.06715912 0.12131587]]
 <NDArray 2x5 @cpu(0)>, 
 [1. 1.]
 <NDArray 2 @cpu(0)>)

In [44]:
num_inputs = 784
def net(X):
    return softmax(nd.dot(X.reshape((-1, num_inputs)), W) + b)

In [46]:
def cross_entropy(yhat, y):
    return - nd.pick(nd.log(yhat, y))

In [47]:
nd.pick?

In [49]:
def accuracy(output, label):
    return nd.mean(output.argmax(axis=1) == label).asscalar()

In [50]:
nd.random_normal?